routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
Route::get('/', function() {
    return redirect('/login');
});

Route::get('login', 'LoginController@view')->name('login');
Route::post('login', 'LoginController@login');

Route::group(
    ['middleware' => 'auth'], function () {
        Route::get('article/list', 'ArticleController@list');
        Route::get('article/detail', 'ArticleController@detail');
        Route::resource('article', 'ArticleController');
        Route::resource('comment', 'CommentController');
    }
);

app/Article.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Article extends Model
{
	protected $guarded = ['id'];

    public function getRouteKeyName()
    {
        return 'slug';
    }

    public function creator()
    {
    	return $this->hasOne('App\User','id','creator');
    }
}

app/Comment.php
<?php

namespace App;

use Illuminate\Database\Eloquent\Model;

class Comment extends Model
{
    protected $guarded = ['id'];
}

app/User.php
<?php

namespace App;

use Illuminate\Contracts\Auth\MustVerifyEmail;
use Illuminate\Foundation\Auth\User as Authenticatable;
use Illuminate\Notifications\Notifiable;

class User extends Authenticatable
{
    use Notifiable;

    /**
     * The attributes that are mass assignable.
     *
     * @var array
     */
    protected $fillable = [
        'name', 'email', 'password',
    ];

    /**
     * The attributes that should be hidden for arrays.
     *
     * @var array
     */
    protected $hidden = [
        'password', 'remember_token',
    ];

    /**
     * The attributes that should be cast to native types.
     *
     * @var array
     */
    protected $casts = [
        'email_verified_at' => 'datetime',
    ];
}

app/Http/Controllers/ArticleController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Article;
use App\Comment;
use Auth;

class ArticleController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $number_of_pages = round(Article::count() / 10);
        return view('article-cms',['number_of_pages'=>$number_of_pages]);
    }

    /**
     * Return list of articles for ajax.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function list(Request $request)
    {
        $articles = Article::orderBy('created_at','desc')
        ->limit(10)
        ->offset(($request->skip - 1) * 10)
        ->get();
        
        return $articles->toArray();
    }

    /**
     * Return detail of article for ajax.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function detail(Request $request)
    {
        $article = Article::with('creator')
        ->where('id',$request->id)
        ->get();

        return response()->json(['code'=>'200','data'=>$article]);
        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        return view('article-add');
    }


    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'name' => 'required',
        'body' => 'required',
        ]);

        Article::create([
        'name'      => $request->name,
        'body'      => $request->body,
        'slug'      => str_slug($request->name),
        'creator'   => Auth::user()->id,
        ]);

        return redirect()->route('article.index')->withMessage('Data Berhasil Di Simpan');
    }

    /**
     * Display the specified resource.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {    
        $article  = Article::findOrFail($id);
        $comments = Comment::where('article_id',$article->id)
        ->get();

        return view('article', compact('article', 'comments'));
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $do = Article::find($id);
        $comment = Comment::where('article_id',$do->id);

        $do->delete();
        $comment->delete();

        return json_encode(true);
    }
}

app/Http/Controllers/CommentController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\Comment;

class CommentController extends Controller
{
    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        $request->validate([
        'body'         => 'required',
        'article_id'   => 'required' 
        ]);

        Comment::create($request->all());
        
        return back()->withMessage('Comment Berhasil Di Simpan');
    }
}

app/Http/Controllers/Controller.php
<?php

namespace App\Http\Controllers;

use Illuminate\Foundation\Auth\Access\AuthorizesRequests;
use Illuminate\Foundation\Bus\DispatchesJobs;
use Illuminate\Foundation\Validation\ValidatesRequests;
use Illuminate\Routing\Controller as BaseController;

class Controller extends BaseController
{
    use AuthorizesRequests, DispatchesJobs, ValidatesRequests;
}

app/Http/Controllers/LoginController.php
<?php

namespace App\Http\Controllers;

use Illuminate\Http\Request;
use App\User;
use Auth;

class LoginController extends Controller
{
    public function view()
    {
        return view('login');
    }

    public function login(Request $request)
    {
        $request->validate([
        'email'   => 'required|email',
        'password'=> 'required'
        ]);

        if (Auth::attempt(['email' => $request->email, 'password' => $request->password])) {
            return redirect()->route('article.index');
        } else {
            // return 'salah';
            return back()->withMessage('Email/Password Salah');
        }
    }
}

resources/views/article-add.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Article CMS</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}" crossorigin="anonymous">
</head>
<body>
    <div class="container">
         @if ($errors->any())
            @foreach($errors->all() as $error)
            <div class="col-md-4">
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ $error }}</strong>
                </div> 
            </div>
            @endforeach
        @endif
        <div class="col-md-12">
            <h1>Add Article</h1>
            
            <form action="{{ route('article.store') }}" method="POST">
                {{ csrf_field() }}   
                <div class="card">
                    <div class="card-header">
                        <h4>Form Article</h4>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label>Article Name</label>
                            <input type="text" name="name" class="form-control" />
                        </div>
                        <div class="form-group">
                            <label>Article Body</label>
                            <textarea type="text" name="body" class="form-control"></textarea>
                        </div>
                         <input type="submit" class="btn btn-primary btn-block" value="Submit" />
                    </div>
                </div>
            </form>
        </div>
    </div>
</body>
</html>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

resources/views/article-cms.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Article CMS</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>

<body>
    <div class="container">
        <h1>Article CMS</h1>
        <a href="{{ route('article.create') }}" class="btn btn-primary">Add Article</a>
        <br>
        <br>

        <table class="table table-bordered">
            <thead>
                <tr>
                    <th>Name</th>
                    <th>Slug</th>
                    <th>Action</th>
                </tr>
            </thead>
            <tbody class="table-body">
               {{-- @foreach($datas as $data)
               <tr>
                   <td>{{ $data->name }}</td>
                   <td>{{ $data->slug }}</td>
                   <td>
                    <div class="btn-group">
                        <a href="#" data-target="#myModal" data-id="{{ $data->id }}" data-toggle="modal" class="btn btn-info btn-detail">Detail</a>
                        <a href="{{ route('article.destroy',$data->id) }}" class="btn btn-danger btn-delete">Delete</a>
                    </div>
                   </td>
               </tr>
               @endforeach  --}}
            </tbody>
        </table>

        <div class="text-center" style="margin-bottom: 50px;">
            <p>Page positon: <span class="page-position">1</span></p>
            <button class="btn btn-primary previous" style="margin-right: 10px;"><</button>
            <button class="btn btn-primary next">></button>
        </div>
    </div>
      
    <div class="modal fade" id="myModal" tab-index="-1">
        <div class="modal-dialog">
            <div class="modal-content">
                <div class="modal-header">
                    <h4 class="modal-title">Article Detail</h4>
                    <button type="button" class="close" data-dismiss="modal">&times;</button>
                </div>
            
                <!-- Modal body -->
                <div class="modal-body">
                    <p>Article Name: <span class="article-name"></span></p>
                    <p>Article Name: <span class="article-slug"></span></p>
                    <p>Creator: <span class="article-creator"></span></p>

                    <a href="" class="article-href" target="_blank">See Page</a>
                </div>
            
                <div class="modal-footer">
                    <button type="button" class="btn btn-danger" data-dismiss="modal">Close</button>
                </div>
            </div>
        </div>
    </div>
</body>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>
<script>
    let page = 1;
    const number_of_page = {{ $number_of_pages }};
    $(document).ready(function () {
        fetchArticle();
        checkPageButton();
    });
    
    /*
    * For fetching data 
    */
    function fetchArticle() {
        fetch('article/list?skip=' + page)
        .then(res => {
            res.json().then(data => {
                populateTable(data);
            });
        });
    }

    /*
    * For fetching article detail
    */
    function fetchArticleDetail(id) {
        fetch('article/detail?id=' + id,{
        }).then(response=>{
            return response.json()
        }).then(data=>{
            if (data['code'] == 200) {
                console.log(data);
                $(".article-name").text(data['data'][0]['name']);
                $(".article-slug").text(data['data'][0]['slug']);
                $(".article-creator").text(data['data'][0]['creator']['name']);
                $(".article-href").attr('href', '{{ url('article/') }}' + '/' + data['data'][0]['id']);
            }
        });
    }

    /*
    * Populate data on table
    */
    function populateTable(data) {
        const table_data = data.map(data => {
            return '<tr><td>'+ data.name +'</td><td>'+ data.slug +'</td><td><div class="btn btn-group"><button class="btn btn-info btn-detail" data-id="'+ data.id +'">Detail</button><button class="btn btn-danger btn-delete" data-id="'+ data.id +'">Delete</button></div></td></tr>'
        });
        $(".table-body").html(table_data);
    }

    /*
    * Move to the previous Page
    */
    $(".previous").click(function() {
        page--;
        fetchArticle();
        $('.page-position').text(page);
        checkPageButton();
    });

    /*
    * Move to the next Page
    */
    $(".next").click(function() {
        page++;
        fetchArticle();
        $('.page-position').text(page);
        checkPageButton();
    });

    /*
    * Check Page Button
    */
    function checkPageButton() {
        if (page == 1) {
           $('.previous').toggle();
           $('.next').show();
        }else{
            if (page == number_of_page) {
                $('.next').toggle();
            }else{
               $('.next').show();
               $('.previous').show();
           }
        }
        console.log(number_of_page);
        console.log(page);
    }

    /*
    * Click to Show Detail of Article
    */
    $(document).on('click','.btn-detail',function (e) {
       e.stopPropagation();
       e.stopImmediatePropagation();
       var id = $(this).attr("data-id");
       fetchArticleDetail(id);
       $('#myModal').modal('show');
    });

    /*
    * Click to Delete Article
    */
    $(document).on('click','.btn-delete',function (e) {
        e.stopPropagation();
        e.stopImmediatePropagation();
        let href = $(this).attr('data-id');
        if (confirm('Anda yakin ingin menghapus?')) {
            fetch('article/' + href, {
                method: 'DELETE',
                headers: {
                    'X-CSRF-TOKEN': "{{ csrf_token() }}",
                }
            }).then(response => {
                fetchArticle();
            })
        }
    });

</script>
</html>

resources/views/article.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Article CMS</title>
    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/css/bootstrap.min.css" integrity="sha384-Gn5384xqQ1aoWXA+058RXPxPg6fy4IWvTNh0E263XmFcJlSAwiGgFAW/dAiS6JXm" crossorigin="anonymous">
</head>
<body>
    <div class="container">
        {{-- @if ($errors->any())
            @foreach($errors->all() as $error)
            <div class="col-md-4">
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ $error }}</strong>
                </div> 
            </div>
            @endforeach
        @endif --}}

        <div class="breadcrumb" style="margin-top:30px">
            <div class="col-md-12">
            <h3>{{ $article->name }}</h3>
            <hr>
            <p>{{ $article->body }}</p>
            <p class="text-right">{{ date('d F Y',strtotime($article->created_at)) }}</p>
        </div>
        </div>
        

        <div class="col-md-8 offset-md-2">
             <h4 class=""> Add Comment</h4>
            <form action="{{ route('comment.store') }}" method="POST">
                @csrf
                <input type="hidden" name="article_id" value="{{ $article->id }}">
                @error('body')
                <small>{{ $message }}</small>
                @enderror
                <textarea class="form-control" name="body"></textarea>
                <br>
                <input type="submit" class="btn btn-primary" value="Submit" />
            </form>
        </div>

        <hr>
        <h2>Comments</h2>
        
        @foreach($comments as $comment)
            <div class="card">
                <div class="card-body">{{ $comment->body }}</div>
            </div>
            <br><br>
        @endforeach
    </div>
</body>
</html>

<script src="https://code.jquery.com/jquery-3.2.1.slim.min.js" integrity="sha384-KJ3o2DKtIkvYIK3UENzmM7KCkRr/rE9/Qpg6aAZGJwFDMVNA/GpGFF93hXpG5KkN" crossorigin="anonymous"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="https://maxcdn.bootstrapcdn.com/bootstrap/4.0.0/js/bootstrap.min.js" integrity="sha384-JZR6Spejh4U02d8jOt6vLEHfe/JQGiRRSQQxSfFWpi1MquVdAyjUar5+76PVCmYl" crossorigin="anonymous"></script>

resources/views/login.blade.php
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <meta http-equiv="X-UA-Compatible" content="ie=edge">
    <title>Article CMS</title>
    <link rel="stylesheet" href="{{ asset('css/app.css') }}" crossorigin="anonymous">
</head>
<body>
    <div class="container">

        @if ($errors->any())
            @foreach($errors->all() as $error)
            <div class="col-md-4">
                <div class="alert alert-danger">
                    <a href="#" class="close" data-dismiss="alert" aria-label="close">&times;</a>
                    <strong>{{ $error }}</strong>
                </div> 
            </div>
            @endforeach
        @endif
        
        <form action="{{ route('login') }}" method="POST">
            @csrf
            <div class="col-md-6 offset-md-3" style="margin-top:120px">
                <div class="card">
                    <div class="card-header">
                        <h3>Login Form</h3>
                    </div>
                    <div class="card-body">
                        <div class="form-group">
                            <label for="">Email</label>
                            <input type="text" name="email" class="form-control" placeholder="email" required="" />
                        </div>
                        <div class="form-group">
                            <label for="">Password</label>
                            <input type="password" name="password" class="form-control" placeholder="password" required="" />
                        </div>
                        <input type="submit" class="btn btn-primary btn-block" value="Submit"/>
                    </div>
                 </div>   
            </div>
        </form>
    </div>
</body>
</html>

<script src="{{ asset('js/jquery.min.js') }}"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.12.9/umd/popper.min.js" integrity="sha384-ApNbgh9B+Y1QKtv3Rn7W3mgPxhU9K/ScQsAP7hUibX39j7fakFPskvXusvfa0b4Q" crossorigin="anonymous"></script>
<script src="{{ asset('js/app.js') }}"></script>